# Docker Profile
spring.datasource.url=jdbc:mysql://mysql:3306/fleet_db
spring.datasource.username=root
spring.datasource.password=${MYSQL_ROOT_PASSWORD:}

# Logging
logging.level.com.evolutech.core.fleet=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=WARN

# Swagger enabled for MVP
springdoc.swagger-ui.enabled=true
